const ASTNodeType = {
  PROGRAM: "PROGRAM",
  VARIABLE_DECLARATION: "VARIABLE_DECLARATION",
  FUNCTION_DECLARATION: "FUNCTION_DECLARATION",
  FUNCTION_CALL: "FUNCTION_CALL", // Add this line
  ASSIGNMENT: "ASSIGNMENT",
  BINARY_EXPRESSION: "BINARY_EXPRESSION",
  IDENTIFIER: "IDENTIFIER",
  LITERAL: "LITERAL",
  BLOCK: "BLOCK",
  IF_STATEMENT: "IF_STATEMENT",
  SWITCH_STATEMENT: "SWITCH_STATEMENT",
  CASE_CLAUSE: "CASE_CLAUSE",
  WHILE_STATEMENT: "WHILE_STATEMENT",
  DO_WHILE_STATEMENT: "DO_WHILE_STATEMENT",
  FOR_STATEMENT: "FOR_STATEMENT",
  RETURN_STATEMENT: "RETURN_STATEMENT",
  BREAK_STATEMENT: "BREAK_STATEMENT",
  CONTINUE_STATEMENT: "CONTINUE_STATEMENT",
  EXPRESSION_STATEMENT: "EXPRESSION_STATEMENT",
};
module.exports = ASTNodeType;
